version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web_chat:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /bin/bash start.sh'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db